-- AlterTable
ALTER TABLE "LogbookEntry" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "location" DROP DEFAULT,
ALTER COLUMN "division" DROP DEFAULT,
ALTER COLUMN "personAssisted" DROP DEFAULT,
ALTER COLUMN "activity" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
